### ISSUE TITLE
Any way to reproduce your Table 6

### ISSUE THREAD

**Issue by CS123n** [tencent-ailab/bddm#2]
Hi, This is very interesting work!
I find that you report pretty good FID results on CIFAR10. I want to know if this repo is the code of audio generation only or if it can be used to reproduce Table 6, too.

**Comment by MaxInGaussian** [comment]
Thanks for your interest. This repo only provides the implementation for the audio generation task. I used a separate code base (developed upon ermongroup/ddim) for image generation, though the training and inference procedures for the schedule network in BDDM are pretty much the same as what is provided here.
