### ISSUE TITLE
VCTK speech recipe

### ISSUE THREAD

**Issue by jerrymatjila** [tencent-ailab/bddm#3]
What is the recipe for reproducing VCTK speech results?

**Comment by MaxInGaussian** [comment]
The network architecture used in the VCTK experiment were the same. We can similarly train a BDDM after modifying the "train_data_dir", "valid_data_dir" & "sampling_rate" in egs/lj/conf.yml. For the ease of reproduction, I will add egs/vctk in the next commit, including the pre-trained models for VCTK.

**Comment by jerrymatjila** [comment]
Thanks. Pre-trained models for VCTK will be highly appreciated.

**Comment by MaxInGaussian** [comment]
You can now find the pretrained models for VCTK at **egs/vctk** in the latest commit. Thanks.
