### ISSUE TITLE
LJSpeech data split

### ISSUE THREAD

**Issue by yahshibu** [tencent-ailab/bddm#5]
Hello, thank you for making your code publicly available!

https://github.com/tencent-ailab/bddm/blob/8c3f807e84f0ebf1a4942a990f369a92cba79c61/egs/lj/conf.yml#L56-L57

I have a question about the data split. How did you split the entire LJSpeech dataset into train/validation sets in your experiment? The original LJSpeech does not have separate train/dev/test sets, but I would like to follow the procedures of your experiment. I'd appreciate it if you would let me know.

Best regards.

**Comment by MaxInGaussian** [comment]
Sure, I have just uploaded the wav lists for validation and evaluation in LJSpeech. Please find them in ``egs/lj``.

**Comment by yahshibu** [comment]
Thank you very much for your kind and prompt response! I appreciate it.
